// Package swagger provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package swagger

// ProductRequest defines model for ProductRequest.
type ProductRequest struct {
	Id    *int64  `json:"id,omitempty"`
	Name  string  `json:"name"`
	Price float32 `json:"price"`
}

// ProductResponse defines model for ProductResponse.
type ProductResponse struct {
	Id *int64 `json:"id,omitempty"`
}

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = ProductRequest
