openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Localhost
paths:
  /product:
    post:
      tags:
        - product
      summary: Create a new product
      operationId: createProduct
      requestBody:
        description: Product to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'

components:
  schemas:
    ProductRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
        price:
          type: number
          format: float
      required:
        - name
        - price

    ProductResponse:
        type: object
        properties:
          id:
            type: integer
            format: int64
            readOnly: true
